<?php
namespace backend\components;
use yii\base\ActionFilter;
use yii\web\HttpException;

class RbacFilter extends ActionFilter{
    public function beforeAction($action)
    {
        $user=\Yii::$app->user;
        if($user->isGuest){
            return $action->controller->redirect(['site/login'])->send();
        }

        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }
}